---
# tasks file for awscli - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ awscli_debian_pre_reqs }} as pre-requisite.
  ansible.builtin.package:
    name: "{{ awscli_debian_pre_reqs }}"
    state: "{{ awscli_debian_pre_reqs_desired_state }}"
    force_apt_get: yes

- name: Debian/Ubuntu Family | Installing {{ awscli_app_debian_package }}
  ansible.builtin.pip:
    executable: "{{ pip_executable }}"
    name: "{{ awscli_app_debian_package }}"
    state: "{{ awscli_desired_state }}"
