---
# tasks file for awscli - Debian

- name: Installing {{ awscli_debian_pre_reqs }} on Debian based systems as pre-requisite.
  package:
    name: "{{ awscli_debian_pre_reqs }}"
    state: "{{ awscli_debian_pre_reqs_desired_state }}"
    force_apt_get: yes

- name: Installing {{ awscli_app_debian_package }} version on Debian based systems.
  pip:
    executable: "{{ pip_executable }}"
    name: "{{ awscli_app_debian_package }}"
    state: "{{ awscli_desired_state }}"
